### obtener todos los eventos
GET http://localhost:4000/api/eventos


### obtener un evento
GET http://localhost:4000/api/eventos/1

### crear un nuevo evento
POST http://localhost:4000/api/eventos
Content-Type: application/json

{
    "id":1,
    "cuposGral":200,
    "eventoCategoria":1,
    "CUIT": 20419513311,
    "nickname": "Duar",
    "password":"asdasdasd1",
    "mail": "joaquingm786@gmail.com"
}


### modificar un evento (PUT - recurso completo e idempotente)
PUT http://localhost:4000/api/eventos/2
Content-Type: application/json


### modificar un evento (PATCH - recurso parcial)
PATCH http://localhost:4000/api/eventos/2
Content-Type: application/json


### borrar un evento
DELETE http://localhost:4000/api/eventos/1