### obtener todos los eventos
GET http://localhost:4000/api/eventos


### obtener un evento
GET http://localhost:4000/api/eventos/1

### crear un nuevo evento
POST http://localhost:4000/api/eventos
Content-Type: application/json

{
    "nombre":"lolapalloza",
    "cuposGral":1234,
    "descripcion":"prueba 1",
    "fotoEvento":0,
    "fecha": 20240312,
    "hora": 14
}


### modificar un evento (PUT - recurso completo e idempotente)
PUT http://localhost:4000/api/eventos/2
Content-Type: application/json


### modificar un evento (PATCH - recurso parcial)
PATCH http://localhost:4000/api/eventos/2
Content-Type: application/json


### borrar un evento
DELETE http://localhost:4000/api/eventos/1