### obtener todos los organizadores
GET http://localhost:3000/api/organizadores


### obtener un organizador
GET http://localhost:3000/api/organizadores/1

### crear un nuevo organizador
POST http://localhost:3000/api/organizadores
Content-Type: application/json


### modificar un organizador (PUT - recurso completo e idempotente)
PUT http://localhost:3000/api/organizadores/2
Content-Type: application/json


### modificar un organizador (PATCH - recurso parcial)
PATCH http://localhost:3000/api/organizadores/2
Content-Type: application/json


### borrar un organizador
DELETE http://localhost:3000/api/organizadores/2