### obtener todas las cuentas

GET http://localhost:3000/api/cuentas 

### obtener una cuenta

GET http://localhost:3000/api/cuentas/101

### crear una nueva cuenta

POST http://localhost:3000/api/cuentas
Content-Type: application/json

{
    "idCuenta": 101,
    "mail":"prueba@gmail.com",
    "nombreU":"cuenta pop",
    "contraseña":"1234",
    "descripcion":"prueba 1",
    "fotoPerfil":0,
}

### modificar una cuenta (PUT - recurso completo e inempotente)
PUT http://localhost:3000/api/cuentas/101
Content-Type: application/json

{
    "mail":"modprueba@gmail.com",
    "nombreU":"cuenta modi",
    "contraseña":"user",
    "descripcion":"prueba 2",
    "fotoPerfil":0,
}
//NO ANDA SI PONGO EL ID EN LA API, SI LO PONGO EN EL JSON SI


### modificar una cuenta (PATCH - recurso parcial)
PATCH http://localhost:3000/api/cuentas/101
Content-Type: application/json

{
    "contraseña":"admin",
    "descripcion": "prueba 3"
}
//NO ANDA SI PONGO EL ID EN LA API, SI LO PONGO EN EL JSON SI


### Borrar una cuenta
DELETE http://localhost:3000/api/cuentas/101
